#include <ch32v00x.h>
#include <debug.h>
#include "hardware.h"
#include "max2769.h"

// Max2769_handler

// Max2769 register addresses
#define MAX_2769_CONF1 0
#define MAX_2769_CONF2 1
#define MAX_2769_CONF3 2
#define MAX_2769_PLLCONF 3
#define MAX_2769_DIV 4
#define MAX_2769_FDIV 5
#define MAX_2769_STRM 6
#define MAX_2769_CLK 7
#define MAX_2769_TEST1 8
#define MAX_2769_TEST2 9


void max2769set(GPIO_TypeDef *cs_port, pin_t cs_pin,
                uint8_t addr,
                uint32_t data)
{

    int i;
    // 32-bit word sent MSB first: the 28 data bits D27..D0, then the 4 address
    // bits A3..A0 (datasheet: "A 32-bit word, with the MSB (D27) being sent
    // first", and the timing diagram shows DATA MSB ... DATA LSB, ADDR MSB ...
    // ADDR LSB). Bits above D27 of data are not part of any register field.
    uint32_t word = ((data & 0x0FFFFFFF) << 4) | (addr & 0x0F);
    GPIO_WriteBit(cs_port, cs_pin, Bit_RESET);
    GPIO_WriteBit(TART_SCLK_PORT, TART_SCLK_PIN, Bit_RESET);

    // Timing parameters from the MAX2769 datasheet, Table 4. The datasheet gives
    // them in nanoseconds (tCSS/tDS/tCSH = 10ns, tCH/tCL = 25ns); they are used
    // here in microseconds, i.e. ~1000x the required minimum, so the bit-banged
    // interface runs far below its speed limit. The remaining Table 4 parameters
    // are covered as follows:
    //   t_DH (data hold after SCLK falls) - satisfied by t_CL below.
    //   t_CSH (last SCLK rising edge -> CS rising edge) - satisfied by Delay_Ms(1)
    //   t_CSW (CS high time >= 1 SCLK period) - satisfied by Delay_Ms(1)
    const int t_CSS = 10;
    const int t_DS = 10;
    const int t_CH = 25;
    const int t_CL = 25;

    Delay_Us(t_CSS); // t_CSS

    for (i = 31; i >= 0; i--)
    {
        uint8_t bit = (word >> i) & 0x00000001L;

        if (0 == bit)
            GPIO_WriteBit(TART_SDATA_PORT, TART_SDATA_PIN, Bit_RESET);
        else
            GPIO_WriteBit(TART_SDATA_PORT, TART_SDATA_PIN, Bit_SET);

        Delay_Us(t_DS); // t_DS = 10
        GPIO_WriteBit(TART_SCLK_PORT, TART_SCLK_PIN, Bit_SET);
        Delay_Us(t_CH); // t_CH = 25
        GPIO_WriteBit(TART_SCLK_PORT, TART_SCLK_PIN, Bit_RESET);
        Delay_Us(t_CL); // t_CL
    }
    GPIO_WriteBit(cs_port, cs_pin, Bit_SET);
    Delay_Ms(1);
}

void setupRadioStream(GPIO_TypeDef *cs_port, pin_t cs_pin)
{
  // Generated by doc/max2769_conf.py --stream
  max2769set(cs_port, cs_pin, 0b0000, 0xa293973);  // CONF1
  max2769set(cs_port, cs_pin, 0b1001, 0x28c0403);  // TEST2: FCENMSB=1 -> IF centre ~4.09MHz
  max2769set(cs_port, cs_pin, 0b0001, 0x855028c);  // CONF2 (2-bit ADC)
  max2769set(cs_port, cs_pin, 0b0010, 0xeaff9e7);  // CONF 3 Streaming: reset
  max2769set(cs_port, cs_pin, 0b0010, 0xeaff9e6);  // CONF 3 Streaming:
  max2769set(cs_port, cs_pin, 0b0011, 0x9ec0008);  // PLL
  max2769set(cs_port, cs_pin, 0b0100, 0x0c00080);  // DIV: NDIV=1536, RDIV=16
  max2769set(cs_port, cs_pin, 0b0111, 0x10061b5);  // CLK
  max2769set(cs_port, cs_pin, 0b0010, 0xeaffde6);  // CONF 3 Streaming: start
  // Deliberately not sent: an STRMRST here (0xeaff9e7) would disturb the frame
  // counters that streaming has just started.
}

void setupRadio(GPIO_TypeDef *cs_port, pin_t cs_pin)
{
  // Generated by doc/max2769_conf.py
  max2769set(cs_port, cs_pin, 0b0000, 0xa293973);  // CONF1
  max2769set(cs_port, cs_pin, 0b1001, 0x28c0403);  // TEST2: FCENMSB=1 -> IF centre ~4.09MHz
  max2769set(cs_port, cs_pin, 0b0001, 0x855020c);  // CONF2
  max2769set(cs_port, cs_pin, 0b0010, 0xeaff1dc);  // CONF3
  max2769set(cs_port, cs_pin, 0b0011, 0x9ec0008);  // PLL
  max2769set(cs_port, cs_pin, 0b0100, 0x0c00080);  // DIV: NDIV=1536, RDIV=16
                                                    // (power-on default, but the
                                                    // datasheet does not guarantee
                                                    // defaults - write it explicitly)
}

void shutdownRadio(void) {
  GPIO_WriteBit(TART_SLOT_ENABLE_PORT, TART_SLOT_ENABLE_PIN, Bit_RESET);  // SHDN# is active low
}

void enableRadio(void) {
  GPIO_WriteBit(TART_SLOT_ENABLE_PORT, TART_SLOT_ENABLE_PIN, Bit_SET); // SHDN# is active low
}
